[package]
name = "vk-alloc"
version = "0.1.0"
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
description = "A collection of Vulkan memory allocators with minimal dependencies."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hasenbanck/vk-alloc"
categories = ["graphics"]
keywords = ["vulkan", "ash"]
edition = "2018"

[dependencies]
ash = "0.31"
slotmap = "1.0"
tracing = { version = "0.1", default-features = false, features = ["std", "max_level_trace", "release_max_level_info"], optional = true }
profiling = { version = "0.1", optional = true }

[features]
profile-with-puffin = ["profiling/profile-with-puffin"]
profile-with-optick = ["profiling/profile-with-optick"]
profile-with-superluminal = ["profiling/profile-with-superluminal"]
profile-with-tracing = ["profiling/profile-with-tracing"]
profile-with-tracy = ["profiling/profile-with-tracy"]

[dev-dependencies]
tracing-subscriber = { version = "0.2", default-features = false, features = ["ansi", "env-filter", "fmt", "registry"] }
